### PR TITLE
FEATURE: API Change, Bug Fixes

### LINKED ISSUE #13: Text node doesn't get wrapped with BoxChild when using spacing

### PR DESCRIPTION
**Pull request by roblafeve**
## Overview

This updates the API and fixes a few issues mentioned below. README has been updated accordingly.

- CHANGE: Separate `element` and `component` props to eliminate overloads
- FIX: `string`/`number` child node should be wrapped in `BoxlChild`
- FIX: Default props should maintain precedence over parent `child*` props
- FEATURE: Add tests for `element` and `component`

>closes #13 

## Review Checklist

- [ ] Merge destination is correct
- [ ] Tests cases have been added where appropriate (Jest, Loki, Cypress)
- [ ] Code is correct as understood and conforms to quality standards

## Testing Instructions

1. Run test suite

### CODE REVIEW

File: src/lib/boxl/test.tsx [hunk 1]
```diff
@@ -7,17 +7,17 @@ describe("boxl", () => {
   const Boxl = b();
```
Comment (roblafeve) [inline src/lib/boxl/test.tsx:9]: Add test for `component` prop

**Review by blaketarter — APPROVED** [review]
